sdk_server_host = "127.0.0.1"
sdk_server_port = 21000

game_server_host = "127.0.0.1"
game_server_port = 23301

dispatch_url = "http://127.0.0.1:21000/query_gateway"

# no need to enable this if you're playing on live version
# since you can just get the update by logging in normally.
enable_auto_hotfix = false

# try changing to "9" or "21" if you get login issues
env_type = "2"
