[package]
name = "uni-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
configs.workspace = true
game-server.workspace = true
sdk-server.workspace = true
tokio.workspace = true
