[package]
name = "game-sv"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
tokio.workspace = true
kcp-zs.workspace = true
