[package]
name = "srtools-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
egui.workspace = true
eframe.workspace = true
open.workspace = true
